# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-datadog-synthetics
  description: This component provides the ability to implement Datadog synthetic tests
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component









